name: build-and-test=Search

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Restore NuGet packages
      working-directory: ./Reclone-Search-Service
      run: dotnet restore

    - name: Build
      working-directory: ./Reclone-Search-Service
      run: dotnet build --configuration Release

    - name: Test
      working-directory: ./Reclone-Search-Service
      run: dotnet test --no-restore --verbosity normal
